CREATE TABLE IF NOT EXISTS USERS(
    id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS AUTHORS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  birth_date VARCHAR(10),
  description TEXT
);

CREATE TABLE IF NOT EXISTS BOOKS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  author INT NOT NULL,
  publication_date VARCHAR(10),
  summary TEXT,
  stock INT DEFAULT 0,
  price DECIMAL(10, 2),
  FOREIGN KEY (author) REFERENCES AUTHORS(id)
);

CREATE TABLE IF NOT EXISTS PURCHASE_HISTORY (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user INT NOT NULL,
  book INT NOT NULL,
  quantity INT NOT NULL,
  total_price DECIMAL(10, 2) NOT NULL,
  payment_timestamp VARCHAR(50) NOT NULL,
  FOREIGN KEY (user) REFERENCES USERS(id),
  FOREIGN KEY (book) REFERENCES BOOKS(id)
);
